apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-gpko
  namespace: rarnaud-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:a7f57884b7222ab8cd16eed0384ec032d667602780aafd860465ff890de5dd86
        name: my-python
        resources: {}
status: {}
